Update config doc on the grafeas note part.
tektoncd/chains pull request #503
Opened 2022-07-29 21:38 UTC by chuangw6

- Added a link to Grafeas doc about notes and occurrences.
- Explained a bit more on how we will use the configurable field
to create notes.

2022-08-10 14:40 UTC, chuangw6 commented
/assign @wlynch
PTAL. Thanks

2022-08-17 15:03 UTC, wlynch requested changes
Totally forgot to hit submit on this yesterday 🤦

2022-08-17 17:56 UTC, chuangw6 commented on docs/config.md
> +|`storage.grafeas.noteid` (optional)|This field will be used as the prefix part of the note name that will be created. The value of this field must be a string without spaces. (See more details below
SG! Added!

2022-08-22 15:45 UTC, wlynch approved these changes

2022-08-22 15:45 UTC, wlynch commented
/lgtm

2022-08-22 15:45 UTC, merged