Record `invocation.configSource` section in slsa provenance
tektoncd/chains pull request #554
Opened 2022-09-09 22:41 UTC by chuangw6

# Changes

Related to https://github.com/tektoncd/chains/issues/521 and https://github.com/tektoncd/pipeline/pull/5397

Prior to this PR, `invocation.configSource` section in slsa provenance was missing.

In this change, we want to record the configSource information in the provenance 
for the remote resources i.e. git, bundle, catalog.

Signed-off-by: Chuang Wang <chuangw@google.com>

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [ ] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [ ] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [ ] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [ ] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [ ] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

``` release-note
NONE
```

2022-09-09 22:42 UTC, chuangw6 commented
/hold

waiting for https://github.com/tektoncd/pipeline/pull/5397

2022-09-12 14:05 UTC, lcarva commented
@chuangw6, I remember a comment from @priyawadhwa that if we populate configSource, we shouldn't update buildConfig. Maybe I misunderstood the comment?

2022-09-12 14:10 UTC, chuangw6 commented
> @chuangw6, I remember a comment from @priyawadhwa that if we populate configSource, we shouldn't update buildConfig. Maybe I misunderstood the comment?

Yeah, I remember that. Talking to @wlynch before, it seems fine to include both sections if we do want to record the remote refs in the provenance.

Thoughts @priyawadhwa @wlynch?

2022-09-12 19:13 UTC, priyawadhwa commented
I'd prefer the provenance be as correct as possible based on the spec. If we can correctly set `configSource` we shouldn't need `buildConfig` anymore!

2022-09-12 19:52 UTC, chuangw6 commented
> I'd prefer the provenance be as correct as possible based on the spec. If we can correctly set `configSource` we shouldn't need `buildConfig` anymore!

That makes sense to me as long as we still record the param values provided by taskrun/pipeline run in the `invocation.parameters` section. So we can
- record `buildConfig` section only for embedded and incluster definition. 
- record `invocation.configSource` section only for remote resources (git, oci, catalog).

But one case I am concerned about is what if the remote resource that user specified in resolver is not retrievable later for some reason. For example, a user specifies git url, commit and pathInRepo correctly in taskrun definition  -> taskrun reconciler fetches the resource -> Chains records it in `invocation.configSource` and leaves `buildConfig` empty -> later the repo that contains the task definition is deleted. In this case, the information recorded in `invocation.configSource` or say the whole provenance will be meaningless. wdyt?

2022-09-13 14:37 UTC, chuangw6 commented
Seems like the slsa0.2 spec doesn't explicitly say the `configSource` and `buildConfig` shouldn't exist simultaneously. In the [Cloud Build example](https://slsa.dev/provenance/v0.2#:~:text=Cloud%20Build%20config%2Das%2Dcode) listed on the website, both sections are filled with content.

2022-09-14 19:28 UTC, priyawadhwa commented
> That makes sense to me as long as we still record the param values provided by taskrun/pipeline run in the invocation.parameters section. 

SGTM.

Re the Cloud Build example, my guess is the example isn't entirely accurate (the Cloud Build RPC example does specify `// Build steps were provided as an argument. No configSource`). The definition for `buildConfig` is:

> Lists the steps in the build. If invocation.configSource is not available, buildConfig can be used to verify information about the build.

and when I added `buildConfig` into the v0.2 spec a few months ago it was definitely intended as an alternative to `configSource`. I don't really see a use case for having both (if a repo is deleted I'd guess you probably just wouldn't trust the artifact at all), but if you feel strongly we can give it a try.

2022-09-15 20:20 UTC, chuangw6 commented
Thanks for the details @priyawadhwa !
I feel like it might be necessary to always keep `buildConfig` section for at least auditing purpose and also for helping reproduce a build. Although we set `invocation.configSource` correctly for the remote definitions, it's possible that the consumer of the provenance does not have the access to the remote repo especially the gitresolver recently supports fetching files from a private repo in https://github.com/tektoncd/pipeline/pull/5450.

2022-09-19 19:27 UTC, wlynch requested changes
@chuangw6 would it be possible to stuff all other fields into `environment`?

The way I see it right now is if PipelineSpec is set, we should set buildConfig, if PipelineRef is set, we set configSource. If there are any values that don't fit nicely with that, let's call those out.

I do see value in recording evaluated specs in the provenance (I'd also like to record the pod that was executed!), but it sounds like the current SLSA 0.2 provenance isn't really meant for that at the moment - this would be a good thing to raise at the SLSA WG.

2022-09-19 19:27 UTC, wlynch commented on pkg/chains/formats/intotoite6/testdata/taskrun2.json
> +        },
Fine for now, but highly recommend working towards making these actual fields in the Run status.

2022-11-28 19:00 UTC, chuangw6 commented
/unhold

2022-11-28 19:03 UTC, chuangw6 commented on pkg/chains/formats/intotoite6/intotoite6.go
> +				"sha256": tr.Status.Annotations["resolution.tekton.dev/revision"],
Thanks for comment. The algorithm is now set in the individual resolvers and differs from resolver to resolver. Please take a look.

2022-11-29 15:25 UTC, wlynch approved these changes
/lgtm

2022-11-29 16:16 UTC, merged