Update cosign to 2.2.0 and pipeline to 0.51.0
tektoncd/chains pull request #921
Opened 2023-09-08 16:24 UTC by lcarva

In order to support keys generated by cosign v2.2.0, we need to use, at least, that version of cosign. This also updates tektoncd/pipeline to its newest version, v0.51.0, to fix a dependency conflict with knative.dev/pkg.

Fixes #918

# Release Notes

``` release-note
NONE
```

2023-09-08 18:59 UTC, lcarva commented
/retest-required

2023-09-08 19:35 UTC, lcarva commented
/retest-required

2023-09-12 16:51 UTC, wlynch requested changes

2023-09-12 17:01 UTC, lcarva commented on .github/workflows/kind-e2e.yaml
> +        - v1.28.x
Done. Thanks!

2023-09-12 17:36 UTC, lcarva commented
@wlynch, this should be all set now.

2023-09-14 15:03 UTC, wlynch approved these changes
/lgtm

2023-09-14 15:04 UTC, merged